In [2]:
import re
import nltk
from nltk.corpus import stopwords

from nltk.stem import WordNetLemmatizer

In [3]:
paragraph = """Introduce yourself, whether in a professional capacity or a casual one, is vital to how people will perceive you for the following interactions that take place. It is essential to create a near-accurate image of yourself in their mind that they feel comfortable and courteous while interacting with you and yet considering that you know what you do.

Whether to say “Hi, I am XYZ” and scratch your head, or say I am this and that is no confident indication of who you are. The right introduction is not too long or too short. It does not have to be a crammed speech. Your introduction does not have to be completely technical or professional."""

In [6]:
lemmatizer=WordNetLemmatizer()

In [7]:
corpus=[]
sentences=nltk.sent_tokenize(paragraph)
for i in range(len(sentences)):
    remove_punc=re.sub('[^a-zA-Z]',' ',sentences[i])
    lower_sentence=remove_punc.lower()
    lower_sentence=lower_sentence.split()
    sentence_clean=[]
    for word in lower_sentence:
        if word not in set(stopwords.words('english')):
            sentence_clean.append(lemmatizer.lemmatize(word))
    review=' '.join(sentence_clean)
    #print(review)
    corpus.append(review)
corpus

['introduce whether professional capacity casual one vital people perceive following interaction take place',
 'essential create near accurate image mind feel comfortable courteous interacting yet considering know',
 'whether say hi xyz scratch head say confident indication',
 'right introduction long short',
 'crammed speech',
 'introduction completely technical professional']

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer()
X = cv.fit_transform(corpus).toarray()

In [9]:
import pandas as pd

pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,0.00000,0.284615,0.284615,0.00000,0.000000,0.000000,0.00000,0.00000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.284615,0.000000,0.284615,0.233388,0.000000,0.00000
1,0.27735,0.000000,0.000000,0.27735,0.000000,0.000000,0.27735,0.27735,0.000000,0.27735,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.27735
2,0.00000,0.000000,0.000000,0.00000,0.000000,0.306104,0.00000,0.00000,0.000000,0.00000,...,0.612207,0.306104,0.000000,0.000000,0.000000,0.000000,0.000000,0.251009,0.306104,0.00000
3,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.00000,0.000000,0.00000,...,0.000000,0.000000,0.521823,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
4,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.00000,0.707107,0.00000,...,0.000000,0.000000,0.000000,0.707107,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
5,0.00000,0.000000,0.000000,0.00000,0.546779,0.000000,0.00000,0.00000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.546779,0.000000,0.000000,0.000000,0.00000